//! descent_core — Rust rewrite of the descent parser generator.
//!
//! Pipeline (mirrors Ruby descent, see rust/PROGRESS.md):
//!   lexer (Tokens) -> parser (AST) -> ir_builder (target-neutral IR)
//!   -> emitter (per-target context + minijinja templates).
//!
//! The production front-end is `reader` (udon-core events -> `Token`s —
//! .desc IS UDON, and udon-core was itself generated by descent, closing the
//! self-hosting loop on the vendored stage-0 in rust/vendor/udon-core). The
//! hand-ported `lexer` module is the differential oracle / fallback
//! (`Frontend::OracleLexer`), kept token-identical on the corpus.

pub mod ast;
pub mod charclass;
pub mod dump;
pub mod emit;
pub mod ir;
pub mod ir_builder;
pub mod lexer;
pub mod parser;
pub mod reader;

pub use ast::Machine;
pub use ir::ParserIR;
pub use ir_builder::{IRBuilder, ValidationError};
pub use lexer::{Lexer, LexerError, Token};
pub use parser::{ParseError, Parser};

/// Front-end selection. `UdonCore` (default) tokenizes via the vendored
/// stage-0 udon-core parser; `OracleLexer` is the hand-ported Ruby lexer,
/// kept as the differential oracle (rust/tools/diff_reader.sh).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Frontend {
    #[default]
    UdonCore,
    OracleLexer,
}

/// Content -> Tokens through the chosen front-end.
pub fn tokenize(
    content: &str,
    source_file: &str,
    frontend: Frontend,
) -> Result<Vec<Token>, LexerError> {
    match frontend {
        Frontend::UdonCore => {
            reader::Reader::tokens(content.as_bytes(), source_file).map(|(tokens, _warnings)| tokens)
        }
        Frontend::OracleLexer => Lexer::new(content, source_file).tokenize(),
    }
}

/// Convenience: content -> AST (default front-end).
pub fn parse(content: &str, source_file: &str) -> Result<Machine, Box<dyn std::error::Error>> {
    parse_with(content, source_file, Frontend::default())
}

/// Content -> AST through the chosen front-end.
pub fn parse_with(
    content: &str,
    source_file: &str,
    frontend: Frontend,
) -> Result<Machine, Box<dyn std::error::Error>> {
    let tokens = tokenize(content, source_file, frontend)?;
    Ok(Parser::new(tokens).parse()?)
}

/// Convenience: content -> target-neutral IR (default front-end).
pub fn build_ir(content: &str, source_file: &str) -> Result<ParserIR, Box<dyn std::error::Error>> {
    build_ir_with(content, source_file, Frontend::default())
}

/// Content -> target-neutral IR through the chosen front-end.
pub fn build_ir_with(
    content: &str,
    source_file: &str,
    frontend: Frontend,
) -> Result<ParserIR, Box<dyn std::error::Error>> {
    let machine = parse_with(content, source_file, frontend)?;
    Ok(IRBuilder::new(&machine).build()?)
}
