#!/usr/bin/env ruby
# frozen_string_literal: true

require 'devex/core'

config = Devex::Core::Configuration.new(
  executable_name: 'descent',
  flag_prefix:     'descent',
  project_markers: %w[.desc Gemfile .git],
  env_prefix:      'DESCENT'
)

cli = Devex::Core::CLI.new(config:)
cli.load_tools(File.expand_path('../lib/descent/tools', __dir__))
exit cli.run(ARGV)
